image:
  file: .gitpod.Dockerfile

ports:
  - port: 3007
    onOpen: open-browser
    visibility: public
  - port: 4000
    onOpen: open-browser
    visibility: public
  - port: 3006
    onOpen: ignore
    visibility: public
  - port: 8080
    onOpen: ignore
    visibility: public

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - graphql.vscode-graphql
    - yzhang.markdown-all-in-one
    - ms-vscode.vscode-typescript-tslint-plugin
    - hediet.vscode-drawio
    - ms-azuretools.vscode-docker

tasks:
  - init: npm run gitpod-init; npm i -g concurrently;
  - command: npx concurrently "npm run gitpod-start" "npx wait-on http-get://localhost:8080/console && npm run gitpod-migrate";
  
